pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        echo 'Checkout Method.....'
        // Checkout your GitHub repository
        git 'https://github.com/ghostonlineq/NextJS-Jenkins.git'
      }
    }

    stage('Install dependencies') {
      steps {
        // Install Node.js dependencies
        sh 'npm install'
      }
    }

    stage('Build') {
      steps {
        // Build the Next.js application
        sh 'npm run build'
      }
    }

    // stage('Test') {
    //   steps {
    //     // Run tests for the Next.js application
    //     sh 'npm run test'
    //   }
    // }

    stage('Deploy') {
      steps {
        // Perform deployment steps here, e.g., deploying to a hosting environment
        // You can use a plugin or custom scripts for deployment
        // Example: sh 'npm run deploy'
        echo 'Start Deploy Application!!!'
      }
    }
  }
}