pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        echo 'Checkout Method.....'
        // Checkout your GitHub repository
       git url: 'https://github.com/ghostonlineq/NextJS-Jenkins.git' , branch: 'main'
      }
    }

    stage('Install dependencies') {
      steps {
        // Install Node.js dependencies (sh for linux, bat for windows)
        echo 'Start Install dependencies'
        bat 'cd my-app && npm install'
      }
    }

    stage('Build') {
      steps {
        // Build the Next.js application
        echo 'Start build project'
        bat 'cd my-app && npm run build'
      }
    }

    stage('Test') {
      steps {
        // Run tests for the Next.js application
        echo 'Start Test project before deploy'
        bat 'cd my-app && npm run test'
      }
    }

    stage('Code Check')

    stage('Deploy') {
      steps {
        // Perform deployment steps here, e.g., deploying to a hosting environment
        // You can use a plugin or custom scripts for deployment
        // Example: sh 'npm run deploy'
        echo 'Start Deploy Application!!!'
      }
    }
  }
}